import React, { useEffect, useState } from 'react';
import { Idea, IdeaAnalysis } from '../types';
import { X, Sparkles, Target, TrendingUp, Code2, DollarSign, Share2, Download, Compass, Check } from 'lucide-react';
import { analyzeIdeaDeepDive, generateIdeaImage, generateRelatedTopics } from '../services/geminiService';
import { RadialBarChart, RadialBar, Legend, Tooltip, ResponsiveContainer } from 'recharts';

interface IdeaDetailModalProps {
  idea: Idea;
  onClose: () => void;
  onExploreRelated: (topic: string) => void;
}

export const IdeaDetailModal: React.FC<IdeaDetailModalProps> = ({ idea, onClose, onExploreRelated }) => {
  const [analysis, setAnalysis] = useState<IdeaAnalysis | null>(null);
  const [loading, setLoading] = useState(true);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [imageLoading, setImageLoading] = useState(false);
  const [relatedTopics, setRelatedTopics] = useState<string[]>([]);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let isMounted = true;
    
    const fetchData = async () => {
      setLoading(true);
      try {
        const [analysisData, relatedData] = await Promise.all([
            analyzeIdeaDeepDive(idea),
            generateRelatedTopics(idea.title)
        ]);
        
        if (isMounted) {
            setAnalysis(analysisData);
            setRelatedTopics(relatedData);
        }
      } catch (error) {
        console.error(error);
      } finally {
        if (isMounted) setLoading(false);
      }
    };

    fetchData();

    return () => { isMounted = false; };
  }, [idea]);

  const handleGenerateImage = async () => {
    if (imageLoading || imageUrl) return;
    setImageLoading(true);
    const url = await generateIdeaImage(idea.title, idea.shortDescription);
    setImageUrl(url);
    setImageLoading(false);
  };

  const handleShare = async () => {
    const shareData = {
        title: idea.title,
        text: `${idea.title}: ${idea.shortDescription}\n\nImpact: ${idea.impactScore}/10 • Feasibility: ${idea.feasibilityScore}/10\n\nGenerated by IdeaFlow AI`,
        url: window.location.href
    };

    if (navigator.share && navigator.canShare && navigator.canShare(shareData)) {
        try {
            await navigator.share(shareData);
        } catch (err) {
            console.debug('Share cancelled or failed', err);
        }
    } else {
        await navigator.clipboard.writeText(`${shareData.title}\n${shareData.text}`);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!analysis) return;
    
    const data = {
        meta: {
            generatedBy: "IdeaFlow AI",
            date: new Date().toISOString()
        },
        idea: idea,
        analysis: analysis,
        relatedTopics: relatedTopics
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${idea.title.replace(/\s+/g, '_').toLowerCase()}_analysis.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Prevent scroll on body when modal is open
  useEffect(() => {
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, []);

  const chartData = analysis ? [
    { name: 'Demand', value: analysis.marketAnalysis.demandLevel, fill: '#14b8a6' },
    { name: 'Growth', value: analysis.marketAnalysis.growthPotential, fill: '#8b5cf6' },
    { name: 'Diff.', value: 100 - analysis.marketAnalysis.difficulty, fill: '#f43f5e' }, // Invert difficulty for "Ease"
  ] : [];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm transition-opacity" onClick={onClose} />
      
      <div className="relative w-full max-w-5xl max-h-[90vh] bg-gray-900 rounded-3xl shadow-2xl overflow-hidden flex flex-col md:flex-row border border-gray-700 animate-fade-in">
        
        {/* Left Column: Visual & Quick Stats */}
        <div className="w-full md:w-1/3 bg-gray-800/50 border-r border-gray-700 p-6 flex flex-col overflow-y-auto scrollbar-hide">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-gray-700 to-gray-600 flex items-center justify-center text-2xl">
              {idea.emoji}
            </div>
            <h2 className="text-xl font-bold text-white leading-tight">{idea.title}</h2>
          </div>

          <div className="aspect-square rounded-2xl bg-gray-900 border border-gray-700 mb-6 flex items-center justify-center overflow-hidden relative group">
            {imageUrl ? (
                <img src={imageUrl} alt={idea.title} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" />
            ) : (
                <div className="text-center p-4">
                    {imageLoading ? (
                         <div className="animate-spin w-8 h-8 border-2 border-brand-500 border-t-transparent rounded-full mx-auto mb-2" />
                    ) : (
                        <button 
                        onClick={handleGenerateImage}
                        className="flex flex-col items-center gap-2 text-gray-400 hover:text-brand-400 transition-colors"
                        >
                        <Sparkles className="w-8 h-8" />
                        <span className="text-sm font-medium">Visualize Idea</span>
                        </button>
                    )}
                </div>
            )}
          </div>

          <div className="space-y-4 mb-8">
            <div className="bg-gray-900/50 p-4 rounded-xl border border-gray-700/50">
              <div className="text-xs text-gray-400 mb-1 uppercase tracking-wider">Feasibility</div>
              <div className="w-full bg-gray-700 h-2 rounded-full overflow-hidden">
                <div className="bg-green-500 h-full rounded-full" style={{ width: `${idea.feasibilityScore * 10}%` }} />
              </div>
            </div>
            <div className="bg-gray-900/50 p-4 rounded-xl border border-gray-700/50">
              <div className="text-xs text-gray-400 mb-1 uppercase tracking-wider">Market Impact</div>
              <div className="w-full bg-gray-700 h-2 rounded-full overflow-hidden">
                <div className="bg-yellow-500 h-full rounded-full" style={{ width: `${idea.impactScore * 10}%` }} />
              </div>
            </div>
          </div>

          <div className="mt-auto">
            <h3 className="text-sm font-semibold text-gray-300 mb-3">Related Topics</h3>
            <div className="flex flex-wrap gap-2">
                {loading && !relatedTopics.length ? (
                    <div className="animate-pulse h-4 w-20 bg-gray-700 rounded" />
                ) : (
                    relatedTopics.map((topic) => (
                        <button 
                            key={topic}
                            onClick={() => onExploreRelated(topic)}
                            className="px-3 py-1.5 text-xs bg-gray-700 hover:bg-brand-600 text-gray-300 hover:text-white rounded-lg transition-colors flex items-center gap-1"
                        >
                            <Compass className="w-3 h-3" /> {topic}
                        </button>
                    ))
                )}
            </div>
          </div>
        </div>

        {/* Right Column: Deep Dive Analysis */}
        <div className="w-full md:w-2/3 p-6 md:p-8 overflow-y-auto relative">
            <button 
                onClick={onClose}
                className="absolute top-6 right-6 p-2 bg-gray-800 rounded-full hover:bg-gray-700 text-gray-400 hover:text-white transition-colors z-10"
            >
                <X className="w-5 h-5" />
            </button>

            {loading ? (
                <div className="space-y-6 animate-pulse mt-8">
                    <div className="h-4 bg-gray-800 rounded w-3/4" />
                    <div className="h-32 bg-gray-800 rounded-xl" />
                    <div className="grid grid-cols-2 gap-4">
                        <div className="h-24 bg-gray-800 rounded-xl" />
                        <div className="h-24 bg-gray-800 rounded-xl" />
                    </div>
                </div>
            ) : analysis ? (
                <div className="space-y-8 animate-fade-in">
                    <div>
                        <h3 className="text-2xl font-bold text-white mb-3">Executive Summary</h3>
                        <p className="text-gray-300 leading-relaxed text-lg">{analysis.detailedDescription}</p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Market Radar */}
                        <div className="bg-gray-800/30 rounded-2xl p-5 border border-gray-700/50">
                            <h4 className="flex items-center gap-2 text-gray-200 font-semibold mb-4">
                                <TrendingUp className="w-5 h-5 text-blue-400" /> Market Analysis
                            </h4>
                            <div className="h-48 w-full">
                                <ResponsiveContainer width="100%" height="100%">
                                    <RadialBarChart 
                                        cx="50%" 
                                        cy="50%" 
                                        innerRadius="20%" 
                                        outerRadius="100%" 
                                        barSize={15} 
                                        data={chartData}
                                    >
                                        <RadialBar
                                            label={{ position: 'insideStart', fill: '#fff' }}
                                            background
                                            dataKey="value"
                                        />
                                        <Legend iconSize={10} layout="vertical" verticalAlign="middle" wrapperStyle={{ right: 0 }} />
                                        <Tooltip 
                                            contentStyle={{ backgroundColor: '#1f2937', border: 'none', borderRadius: '8px' }}
                                            itemStyle={{ color: '#fff' }}
                                        />
                                    </RadialBarChart>
                                </ResponsiveContainer>
                            </div>
                            <div className="grid grid-cols-2 gap-4 mt-2 text-center">
                                <div className="bg-gray-900/50 p-2 rounded-lg">
                                    <div className="text-xs text-gray-500">Competition</div>
                                    <div className="font-bold text-brand-400">{analysis.marketAnalysis.competitorCount}</div>
                                </div>
                                <div className="bg-gray-900/50 p-2 rounded-lg">
                                    <div className="text-xs text-gray-500">Difficulty</div>
                                    <div className="font-bold text-red-400">{analysis.marketAnalysis.difficulty}/100</div>
                                </div>
                            </div>
                        </div>

                        {/* Target Audience */}
                        <div className="bg-gray-800/30 rounded-2xl p-5 border border-gray-700/50">
                             <h4 className="flex items-center gap-2 text-gray-200 font-semibold mb-4">
                                <Target className="w-5 h-5 text-purple-400" /> Target Audience
                            </h4>
                            <ul className="space-y-2">
                                {analysis.targetAudience.map((aud, i) => (
                                    <li key={i} className="flex items-start gap-2 text-sm text-gray-300">
                                        <span className="w-1.5 h-1.5 rounded-full bg-purple-500 mt-1.5 flex-shrink-0" />
                                        {aud}
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Tech Stack */}
                        <div>
                            <h4 className="flex items-center gap-2 text-gray-200 font-semibold mb-4">
                                <Code2 className="w-5 h-5 text-pink-400" /> Tech Stack
                            </h4>
                            <div className="flex flex-wrap gap-2">
                                {analysis.techStackRecommendation.map((tech, i) => (
                                    <span key={i} className="px-3 py-1.5 bg-pink-500/10 text-pink-300 border border-pink-500/20 rounded-lg text-sm font-mono">
                                        {tech}
                                    </span>
                                ))}
                            </div>
                        </div>

                        {/* Revenue */}
                        <div>
                            <h4 className="flex items-center gap-2 text-gray-200 font-semibold mb-4">
                                <DollarSign className="w-5 h-5 text-green-400" /> Revenue Models
                            </h4>
                            <div className="space-y-2">
                                {analysis.revenueModels.map((model, i) => (
                                    <div key={i} className="flex items-center gap-2 text-sm text-gray-300 bg-gray-800/50 p-2 rounded-lg">
                                        <div className="w-1 h-4 bg-green-500 rounded-full" />
                                        {model}
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    <div className="pt-6 border-t border-gray-800">
                        <h4 className="text-gray-400 text-sm uppercase tracking-wider mb-4 font-semibold">Action Plan</h4>
                        <div className="space-y-4">
                            {analysis.nextSteps.map((step, i) => (
                                <div key={i} className="flex items-start gap-4">
                                    <div className="w-6 h-6 rounded-full bg-brand-900 text-brand-400 border border-brand-700 flex items-center justify-center text-xs font-bold flex-shrink-0">
                                        {i + 1}
                                    </div>
                                    <p className="text-gray-300 text-sm">{step}</p>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="flex gap-4 pt-4">
                         <button 
                            onClick={handleShare}
                            className="flex-1 py-3 bg-brand-600 hover:bg-brand-500 text-white rounded-xl font-semibold transition-colors flex items-center justify-center gap-2 shadow-lg shadow-brand-900/50"
                         >
                            {copied ? <Check className="w-4 h-4" /> : <Share2 className="w-4 h-4" />}
                            {copied ? 'Copied!' : 'Share Idea'}
                         </button>
                         <button 
                            onClick={handleDownload}
                            className="px-6 py-3 bg-gray-800 hover:bg-gray-700 text-white rounded-xl font-semibold transition-colors border border-gray-700 flex items-center gap-2"
                         >
                            <Download className="w-4 h-4" />
                            <span className="hidden sm:inline">Export JSON</span>
                         </button>
                    </div>
                </div>
            ) : null}
        </div>
      </div>
    </div>
  );
};